In [94]:
import pandas as pd
import numpy as np

In [78]:
#load data from CSV with unicode encoding
df = pandas.read_csv("C:\\Users\\hempe\\Studium\\Masterthesis\\Repository\\Masterthesis\\data\\raw\\BindingDB_BindingDB_Articles.tsv", sep='\t', encoding='utf-8')

C:\Users\hempe\AppData\Local\Temp\ipykernel_27880\3367166347.py:2: DtypeWarning: Columns (0: Ki (nM), 1: IC50 (nM), 2: Kd (nM), 3: EC50 (nM), 4: koff (s-1), 5: Temp (C), 6: Article DOI, 7: PubChem AID, 8: Authors, 9: Institution, 10: Ligand HET ID in PDB, 11: PDB ID(s) for Ligand-Target Complex, 12: ChEMBL ID of Ligand, 13: DrugBank ID of Ligand, 14: KEGG ID of Ligand, 15: ZINC ID of Ligand, 16: UniProt (SwissProt) Secondary ID(s) of Target Chain 1, 17: UniProt (TrEMBL) Submitted Name of Target Chain 1, 18: UniProt (TrEMBL) Entry Name of Target Chain 1, 19: UniProt (TrEMBL) Primary ID of Target Chain 1, 20: UniProt (TrEMBL) Secondary ID(s) of Target Chain 1, 21: BindingDB Target Chain Sequence 2, 22: PDB ID(s) of Target Chain 2, 23: UniProt (SwissProt) Recommended Name of Target Chain 2, 24: UniProt (SwissProt) Entry Name of Target Chain 2, 25: UniProt (SwissProt) Primary ID of Target Chain 2, 26: UniProt (SwissProt) Secondary ID(s) of Target Chain 2, 27: UniProt (TrEMBL) Submitted Name of Target Chain 2, 28: UniProt (TrEMBL) Entry Name of Target Chain 2, 29: UniProt (TrEMBL) Primary ID of Target Chain 2, 30: UniProt (TrEMBL) Secondary ID(s) of Target Chain 2, 31: BindingDB Target Chain Sequence 3, 32: PDB ID(s) of Target Chain 3, 33: UniProt (SwissProt) Recommended Name of Target Chain 3, 34: UniProt (SwissProt) Entry Name of Target Chain 3, 35: UniProt (SwissProt) Primary ID of Target Chain 3, 36: UniProt (SwissProt) Secondary ID(s) of Target Chain 3, 37: UniProt (TrEMBL) Submitted Name of Target Chain 3, 38: UniProt (TrEMBL) Entry Name of Target Chain 3, 39: UniProt (TrEMBL) Primary ID of Target Chain 3, 40: UniProt (TrEMBL) Secondary ID(s) of Target Chain 3, 41: BindingDB Target Chain Sequence 4, 42: PDB ID(s) of Target Chain 4, 43: UniProt (SwissProt) Recommended Name of Target Chain 4, 44: UniProt (SwissProt) Entry Name of Target Chain 4, 45: UniProt (SwissProt) Primary ID of Target Chain 4, 46: UniProt (SwissProt) Secondary ID(s) of Target Chain 4, 47: BindingDB Target Chain Sequence 5, 48: PDB ID(s) of Target Chain 5, 49: UniProt (SwissProt) Recommended Name of Target Chain 5, 50: UniProt (SwissProt) Entry Name of Target Chain 5, 51: UniProt (SwissProt) Primary ID of Target Chain 5, 52: UniProt (SwissProt) Secondary ID(s) of Target Chain 5, 53: BindingDB Target Chain Sequence 6, 54: PDB ID(s) of Target Chain 6, 55: UniProt (SwissProt) Recommended Name of Target Chain 6, 56: UniProt (SwissProt) Entry Name of Target Chain 6, 57: UniProt (SwissProt) Primary ID of Target Chain 6, 58: UniProt (SwissProt) Secondary ID(s) of Target Chain 6, 59: BindingDB Target Chain Sequence 7, 60: UniProt (SwissProt) Recommended Name of Target Chain 7, 61: UniProt (SwissProt) Entry Name of Target Chain 7, 62: UniProt (SwissProt) Primary ID of Target Chain 7, 63: UniProt (SwissProt) Secondary ID(s) of Target Chain 7, 64: BindingDB Target Chain Sequence 8, 65: PDB ID(s) of Target Chain 8, 66: UniProt (SwissProt) Recommended Name of Target Chain 8, 67: UniProt (SwissProt) Entry Name of Target Chain 8, 68: UniProt (SwissProt) Primary ID of Target Chain 8, 69: UniProt (SwissProt) Secondary ID(s) of Target Chain 8, 70: BindingDB Target Chain Sequence 9, 71: UniProt (SwissProt) Recommended Name of Target Chain 9, 72: UniProt (SwissProt) Entry Name of Target Chain 9, 73: UniProt (SwissProt) Primary ID of Target Chain 9, 74: UniProt (SwissProt) Secondary ID(s) of Target Chain 9, 75: BindingDB Target Chain Sequence 10, 76: UniProt (SwissProt) Recommended Name of Target Chain 10, 77: UniProt (SwissProt) Entry Name of Target Chain 10, 78: UniProt (SwissProt) Primary ID of Target Chain 10, 79: UniProt (SwissProt) Secondary ID(s) of Target Chain 10, 80: BindingDB Target Chain Sequence 11, 81: PDB ID(s) of Target Chain 11, 82: UniProt (SwissProt) Recommended Name of Target Chain 11, 83: UniProt (SwissProt) Entry Name of Target Chain 11, 84: UniProt (SwissProt) Primary ID of Target Chain 11, 85: UniProt (SwissProt) Secondary ID(s) of Target Chain 11) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pandas.read_csv("C:\\Users\\hempe\\Studium\\Masterthesis\\Repository\\Masterthesis\\data\\raw\\BindingDB_BindingDB_Articles.tsv", sep='\t', encoding='utf-8')

In [79]:
# filter all data where IC50 (nM) is not null
df = df[df['IC50 (nM)'].notnull()]
#filter all data where BindingDB Target Chain Sequence 1 is not null
df = df[df['BindingDB Target Chain Sequence 1'].notnull()]
#filter all data where Ligand SMILES is not null
df = df[df['Ligand SMILES'].notnull()]
#filter all data where IC50 (nM) is not numeric
df = df[pandas.to_numeric(df['IC50 (nM)'], errors='coerce').notnull()]

In [80]:
df.columns.tolist()

['BindingDB Reactant_set_id',
 'Ligand SMILES',
 'Ligand InChI',
 'Ligand InChI Key',
 'BindingDB MonomerID',
 'BindingDB Ligand Name',
 'Target Name',
 'Target Source Organism According to Curator or DataSource',
 'Ki (nM)',
 'IC50 (nM)',
 'Kd (nM)',
 'EC50 (nM)',
 'kon (M-1-s-1)',
 'koff (s-1)',
 'pH',
 'Temp (C)',
 'Curation/DataSource',
 'Article DOI',
 'BindingDB Entry DOI',
 'PMID',
 'PubChem AID',
 'Patent Number',
 'Authors',
 'Date of publication',
 'Date in BindingDB',
 'Institution',
 'Link to Ligand in BindingDB',
 'Link to Target in BindingDB',
 'Link to Ligand-Target Pair in BindingDB',
 'Ligand HET ID in PDB',
 'PDB ID(s) for Ligand-Target Complex',
 'PubChem CID',
 'PubChem SID',
 'ChEBI ID of Ligand',
 'ChEMBL ID of Ligand',
 'DrugBank ID of Ligand',
 'IUPHAR_GRAC ID of Ligand',
 'KEGG ID of Ligand',
 'ZINC ID of Ligand',
 'Number of Protein Chains in Target (>1 implies a multichain complex)',
 'BindingDB Target Chain Sequence 1',
 'PDB ID(s) of Target Chain 1',
 'UniProt (SwissProt) Recommended Name of Target Chain 1',
 'UniProt (SwissProt) Entry Name of Target Chain 1',
 'UniProt (SwissProt) Primary ID of Target Chain 1',
 'UniProt (SwissProt) Secondary ID(s) of Target Chain 1',
 'UniProt (SwissProt) Alternative ID(s) of Target Chain 1',
 'UniProt (TrEMBL) Submitted Name of Target Chain 1',
 'UniProt (TrEMBL) Entry Name of Target Chain 1',
 'UniProt (TrEMBL) Primary ID of Target Chain 1',
 'UniProt (TrEMBL) Secondary ID(s) of Target Chain 1',
 'UniProt (TrEMBL) Alternative ID(s) of Target Chain 1',
 'BindingDB Target Chain Sequence 2',
 'PDB ID(s) of Target Chain 2',
 'UniProt (SwissProt) Recommended Name of Target Chain 2',
 'UniProt (SwissProt) Entry Name of Target Chain 2',
 'UniProt (SwissProt) Primary ID of Target Chain 2',
 'UniProt (SwissProt) Secondary ID(s) of Target Chain 2',
 'UniProt (SwissProt) Alternative ID(s) of Target Chain 2',
 'UniProt (TrEMBL) Submitted Name of Target Chain 2',
 'UniProt (TrEMBL) Entry Name of Target Chain 2',
 'UniProt (TrEMBL) Primary ID of Target Chain 2',
 'UniProt (TrEMBL) Secondary ID(s) of Target Chain 2',
 'UniProt (TrEMBL) Alternative ID(s) of Target Chain 2',
 'BindingDB Target Chain Sequence 3',
 'PDB ID(s) of Target Chain 3',
 'UniProt (SwissProt) Recommended Name of Target Chain 3',
 'UniProt (SwissProt) Entry Name of Target Chain 3',
 'UniProt (SwissProt) Primary ID of Target Chain 3',
 'UniProt (SwissProt) Secondary ID(s) of Target Chain 3',
 'UniProt (SwissProt) Alternative ID(s) of Target Chain 3',
 'UniProt (TrEMBL) Submitted Name of Target Chain 3',
 'UniProt (TrEMBL) Entry Name of Target Chain 3',
 'UniProt (TrEMBL) Primary ID of Target Chain 3',
 'UniProt (TrEMBL) Secondary ID(s) of Target Chain 3',
 'UniProt (TrEMBL) Alternative ID(s) of Target Chain 3',
 'BindingDB Target Chain Sequence 4',
 'PDB ID(s) of Target Chain 4',
 'UniProt (SwissProt) Recommended Name of Target Chain 4',
 'UniProt (SwissProt) Entry Name of Target Chain 4',
 'UniProt (SwissProt) Primary ID of Target Chain 4',
 'UniProt (SwissProt) Secondary ID(s) of Target Chain 4',
 'UniProt (SwissProt) Alternative ID(s) of Target Chain 4',
 'UniProt (TrEMBL) Submitted Name of Target Chain 4',
 'UniProt (TrEMBL) Entry Name of Target Chain 4',
 'UniProt (TrEMBL) Primary ID of Target Chain 4',
 'UniProt (TrEMBL) Secondary ID(s) of Target Chain 4',
 'UniProt (TrEMBL) Alternative ID(s) of Target Chain 4',
 'BindingDB Target Chain Sequence 5',
 'PDB ID(s) of Target Chain 5',
 'UniProt (SwissProt) Recommended Name of Target Chain 5',
 'UniProt (SwissProt) Entry Name of Target Chain 5',
 'UniProt (SwissProt) Primary ID of Target Chain 5',
 'UniProt (SwissProt) Secondary ID(s) of Target Chain 5',
 'UniProt (SwissProt) Alternative ID(s) of Target Chain 5',
 'UniProt (TrEMBL) Submitted Name of Target Chain 5',
 'UniProt (TrEMBL) Entry Name of Target Chain 5',
 'UniProt (TrEMBL) Primary ID of Target Chain 5',
 'UniProt (TrEMBL) Secondary ID(s) of Target Chain 5',
 'UniProt (TrEMBL) Alternative ID(s) of Target Chain 5',
 'BindingDB Target Chain Sequence 6',
 'PDB ID(s) of Target Chain 6',
 'UniProt (SwissProt) Recommended Name of Target Chain 6',
 'UniProt (SwissProt) Entry Name of Target Chain 6',
 'UniProt (SwissProt) Primary ID of Target Chain 6',
 'UniProt (SwissProt) Secondary ID(s) of Target Chain 6',
 'UniProt (SwissProt) Alternative ID(s) of Target Chain 6',
 'UniProt (TrEMBL) Submitted Name of Target Chain 6',
 'UniProt (TrEMBL) Entry Name of Target Chain 6',
 'UniProt (TrEMBL) Primary ID of Target Chain 6',
 'UniProt (TrEMBL) Secondary ID(s) of Target Chain 6',
 'UniProt (TrEMBL) Alternative ID(s) of Target Chain 6',
 'BindingDB Target Chain Sequence 7',
 'PDB ID(s) of Target Chain 7',
 'UniProt (SwissProt) Recommended Name of Target Chain 7',
 'UniProt (SwissProt) Entry Name of Target Chain 7',
 'UniProt (SwissProt) Primary ID of Target Chain 7',
 'UniProt (SwissProt) Secondary ID(s) of Target Chain 7',
 'UniProt (SwissProt) Alternative ID(s) of Target Chain 7',
 'UniProt (TrEMBL) Submitted Name of Target Chain 7',
 'UniProt (TrEMBL) Entry Name of Target Chain 7',
 'UniProt (TrEMBL) Primary ID of Target Chain 7',
 'UniProt (TrEMBL) Secondary ID(s) of Target Chain 7',
 'UniProt (TrEMBL) Alternative ID(s) of Target Chain 7',
 'BindingDB Target Chain Sequence 8',
 'PDB ID(s) of Target Chain 8',
 'UniProt (SwissProt) Recommended Name of Target Chain 8',
 'UniProt (SwissProt) Entry Name of Target Chain 8',
 'UniProt (SwissProt) Primary ID of Target Chain 8',
 'UniProt (SwissProt) Secondary ID(s) of Target Chain 8',
 'UniProt (SwissProt) Alternative ID(s) of Target Chain 8',
 'UniProt (TrEMBL) Submitted Name of Target Chain 8',
 'UniProt (TrEMBL) Entry Name of Target Chain 8',
 'UniProt (TrEMBL) Primary ID of Target Chain 8',
 'UniProt (TrEMBL) Secondary ID(s) of Target Chain 8',
 'UniProt (TrEMBL) Alternative ID(s) of Target Chain 8',
 'BindingDB Target Chain Sequence 9',
 'PDB ID(s) of Target Chain 9',
 'UniProt (SwissProt) Recommended Name of Target Chain 9',
 'UniProt (SwissProt) Entry Name of Target Chain 9',
 'UniProt (SwissProt) Primary ID of Target Chain 9',
 'UniProt (SwissProt) Secondary ID(s) of Target Chain 9',
 'UniProt (SwissProt) Alternative ID(s) of Target Chain 9',
 'UniProt (TrEMBL) Submitted Name of Target Chain 9',
 'UniProt (TrEMBL) Entry Name of Target Chain 9',
 'UniProt (TrEMBL) Primary ID of Target Chain 9',
 'UniProt (TrEMBL) Secondary ID(s) of Target Chain 9',
 'UniProt (TrEMBL) Alternative ID(s) of Target Chain 9',
 'BindingDB Target Chain Sequence 10',
 'PDB ID(s) of Target Chain 10',
 'UniProt (SwissProt) Recommended Name of Target Chain 10',
 'UniProt (SwissProt) Entry Name of Target Chain 10',
 'UniProt (SwissProt) Primary ID of Target Chain 10',
 'UniProt (SwissProt) Secondary ID(s) of Target Chain 10',
 'UniProt (SwissProt) Alternative ID(s) of Target Chain 10',
 'UniProt (TrEMBL) Submitted Name of Target Chain 10',
 'UniProt (TrEMBL) Entry Name of Target Chain 10',
 'UniProt (TrEMBL) Primary ID of Target Chain 10',
 'UniProt (TrEMBL) Secondary ID(s) of Target Chain 10',
 'UniProt (TrEMBL) Alternative ID(s) of Target Chain 10',
 'BindingDB Target Chain Sequence 11',
 'PDB ID(s) of Target Chain 11',
 'UniProt (SwissProt) Recommended Name of Target Chain 11',
 'UniProt (SwissProt) Entry Name of Target Chain 11',
 'UniProt (SwissProt) Primary ID of Target Chain 11',
 'UniProt (SwissProt) Secondary ID(s) of Target Chain 11',
 'UniProt (SwissProt) Alternative ID(s) of Target Chain 11',
 'UniProt (TrEMBL) Submitted Name of Target Chain 11',
 'UniProt (TrEMBL) Entry Name of Target Chain 11',
 'UniProt (TrEMBL) Primary ID of Target Chain 11',
 'UniProt (TrEMBL) Secondary ID(s) of Target Chain 11',
 'UniProt (TrEMBL) Alternative ID(s) of Target Chain 11',
 'BindingDB Target Chain Sequence 12',
 'PDB ID(s) of Target Chain 12',
 'UniProt (SwissProt) Recommended Name of Target Chain 12',
 'UniProt (SwissProt) Entry Name of Target Chain 12',
 'UniProt (SwissProt) Primary ID of Target Chain 12',
 'UniProt (SwissProt) Secondary ID(s) of Target Chain 12',
 'UniProt (SwissProt) Alternative ID(s) of Target Chain 12',
 'UniProt (TrEMBL) Submitted Name of Target Chain 12',
 'UniProt (TrEMBL) Entry Name of Target Chain 12',
 'UniProt (TrEMBL) Primary ID of Target Chain 12',
 'UniProt (TrEMBL) Secondary ID(s) of Target Chain 12',
 'UniProt (TrEMBL) Alternative ID(s) of Target Chain 12',
 'BindingDB Target Chain Sequence 13',
 'PDB ID(s) of Target Chain 13',
 'UniProt (SwissProt) Recommended Name of Target Chain 13',
 'UniProt (SwissProt) Entry Name of Target Chain 13',
 'UniProt (SwissProt) Primary ID of Target Chain 13',
 'UniProt (SwissProt) Secondary ID(s) of Target Chain 13',
 'UniProt (SwissProt) Alternative ID(s) of Target Chain 13',
 'UniProt (TrEMBL) Submitted Name of Target Chain 13',
 'UniProt (TrEMBL) Entry Name of Target Chain 13',
 'UniProt (TrEMBL) Primary ID of Target Chain 13',
 'UniProt (TrEMBL) Secondary ID(s) of Target Chain 13',
 'UniProt (TrEMBL) Alternative ID(s) of Target Chain 13',
 'BindingDB Target Chain Sequence 14',
 'PDB ID(s) of Target Chain 14',
 'UniProt (SwissProt) Recommended Name of Target Chain 14',
 'UniProt (SwissProt) Entry Name of Target Chain 14',
 'UniProt (SwissProt) Primary ID of Target Chain 14',
 'UniProt (SwissProt) Secondary ID(s) of Target Chain 14',
 'UniProt (SwissProt) Alternative ID(s) of Target Chain 14',
 'UniProt (TrEMBL) Submitted Name of Target Chain 14',
 'UniProt (TrEMBL) Entry Name of Target Chain 14',
 'UniProt (TrEMBL) Primary ID of Target Chain 14',
 'UniProt (TrEMBL) Secondary ID(s) of Target Chain 14',
 'UniProt (TrEMBL) Alternative ID(s) of Target Chain 14',
 'BindingDB Target Chain Sequence 15',
 'PDB ID(s) of Target Chain 15',
 'UniProt (SwissProt) Recommended Name of Target Chain 15',
 'UniProt (SwissProt) Entry Name of Target Chain 15',
 'UniProt (SwissProt) Primary ID of Target Chain 15',
 'UniProt (SwissProt) Secondary ID(s) of Target Chain 15',
 'UniProt (SwissProt) Alternative ID(s) of Target Chain 15',
 'UniProt (TrEMBL) Submitted Name of Target Chain 15',
 'UniProt (TrEMBL) Entry Name of Target Chain 15',
 'UniProt (TrEMBL) Primary ID of Target Chain 15',
 'UniProt (TrEMBL) Secondary ID(s) of Target Chain 15',
 'UniProt (TrEMBL) Alternative ID(s) of Target Chain 15',
 'BindingDB Target Chain Sequence 16',
 'PDB ID(s) of Target Chain 16',
 'UniProt (SwissProt) Recommended Name of Target Chain 16',
 'UniProt (SwissProt) Entry Name of Target Chain 16',
 'UniProt (SwissProt) Primary ID of Target Chain 16',
 'UniProt (SwissProt) Secondary ID(s) of Target Chain 16',
 'UniProt (SwissProt) Alternative ID(s) of Target Chain 16',
 'UniProt (TrEMBL) Submitted Name of Target Chain 16',
 'UniProt (TrEMBL) Entry Name of Target Chain 16',
 'UniProt (TrEMBL) Primary ID of Target Chain 16',
 'UniProt (TrEMBL) Secondary ID(s) of Target Chain 16',
 'UniProt (TrEMBL) Alternative ID(s) of Target Chain 16',
 'BindingDB Target Chain Sequence 17',
 'PDB ID(s) of Target Chain 17',
 'UniProt (SwissProt) Recommended Name of Target Chain 17',
 'UniProt (SwissProt) Entry Name of Target Chain 17',
 'UniProt (SwissProt) Primary ID of Target Chain 17',
 'UniProt (SwissProt) Secondary ID(s) of Target Chain 17',
 'UniProt (SwissProt) Alternative ID(s) of Target Chain 17',
 'UniProt (TrEMBL) Submitted Name of Target Chain 17',
 'UniProt (TrEMBL) Entry Name of Target Chain 17',
 'UniProt (TrEMBL) Primary ID of Target Chain 17',
 'UniProt (TrEMBL) Secondary ID(s) of Target Chain 17',
 'UniProt (TrEMBL) Alternative ID(s) of Target Chain 17',
 'BindingDB Target Chain Sequence 18',
 'PDB ID(s) of Target Chain 18',
 'UniProt (SwissProt) Recommended Name of Target Chain 18',
 'UniProt (SwissProt) Entry Name of Target Chain 18',
 'UniProt (SwissProt) Primary ID of Target Chain 18',
 'UniProt (SwissProt) Secondary ID(s) of Target Chain 18',
 'UniProt (SwissProt) Alternative ID(s) of Target Chain 18',
 'UniProt (TrEMBL) Submitted Name of Target Chain 18',
 'UniProt (TrEMBL) Entry Name of Target Chain 18',
 'UniProt (TrEMBL) Primary ID of Target Chain 18',
 'UniProt (TrEMBL) Secondary ID(s) of Target Chain 18',
 'UniProt (TrEMBL) Alternative ID(s) of Target Chain 18',
 'BindingDB Target Chain Sequence 19',
 'PDB ID(s) of Target Chain 19',
 'UniProt (SwissProt) Recommended Name of Target Chain 19',
 'UniProt (SwissProt) Entry Name of Target Chain 19',
 'UniProt (SwissProt) Primary ID of Target Chain 19',
 'UniProt (SwissProt) Secondary ID(s) of Target Chain 19',
 'UniProt (SwissProt) Alternative ID(s) of Target Chain 19',
 'UniProt (TrEMBL) Submitted Name of Target Chain 19',
 'UniProt (TrEMBL) Entry Name of Target Chain 19',
 'UniProt (TrEMBL) Primary ID of Target Chain 19',
 'UniProt (TrEMBL) Secondary ID(s) of Target Chain 19',
 'UniProt (TrEMBL) Alternative ID(s) of Target Chain 19',
 'BindingDB Target Chain Sequence 20',
 'PDB ID(s) of Target Chain 20',
 'UniProt (SwissProt) Recommended Name of Target Chain 20',
 'UniProt (SwissProt) Entry Name of Target Chain 20',
 'UniProt (SwissProt) Primary ID of Target Chain 20',
 'UniProt (SwissProt) Secondary ID(s) of Target Chain 20',
 'UniProt (SwissProt) Alternative ID(s) of Target Chain 20',
 'UniProt (TrEMBL) Submitted Name of Target Chain 20',
 'UniProt (TrEMBL) Entry Name of Target Chain 20',
 'UniProt (TrEMBL) Primary ID of Target Chain 20',
 'UniProt (TrEMBL) Secondary ID(s) of Target Chain 20',
 'UniProt (TrEMBL) Alternative ID(s) of Target Chain 20',
 'BindingDB Target Chain Sequence 21',
 'PDB ID(s) of Target Chain 21',
 'UniProt (SwissProt) Recommended Name of Target Chain 21',
 'UniProt (SwissProt) Entry Name of Target Chain 21',
 'UniProt (SwissProt) Primary ID of Target Chain 21',
 'UniProt (SwissProt) Secondary ID(s) of Target Chain 21',
 'UniProt (SwissProt) Alternative ID(s) of Target Chain 21',
 'UniProt (TrEMBL) Submitted Name of Target Chain 21',
 'UniProt (TrEMBL) Entry Name of Target Chain 21',
 'UniProt (TrEMBL) Primary ID of Target Chain 21',
 'UniProt (TrEMBL) Secondary ID(s) of Target Chain 21',
 'UniProt (TrEMBL) Alternative ID(s) of Target Chain 21',
 'BindingDB Target Chain Sequence 22',
 'PDB ID(s) of Target Chain 22',
 'UniProt (SwissProt) Recommended Name of Target Chain 22',
 'UniProt (SwissProt) Entry Name of Target Chain 22',
 'UniProt (SwissProt) Primary ID of Target Chain 22',
 'UniProt (SwissProt) Secondary ID(s) of Target Chain 22',
 'UniProt (SwissProt) Alternative ID(s) of Target Chain 22',
 'UniProt (TrEMBL) Submitted Name of Target Chain 22',
 'UniProt (TrEMBL) Entry Name of Target Chain 22',
 'UniProt (TrEMBL) Primary ID of Target Chain 22',
 'UniProt (TrEMBL) Secondary ID(s) of Target Chain 22',
 'UniProt (TrEMBL) Alternative ID(s) of Target Chain 22',
 'BindingDB Target Chain Sequence 23',
 'PDB ID(s) of Target Chain 23',
 'UniProt (SwissProt) Recommended Name of Target Chain 23',
 'UniProt (SwissProt) Entry Name of Target Chain 23',
 'UniProt (SwissProt) Primary ID of Target Chain 23',
 'UniProt (SwissProt) Secondary ID(s) of Target Chain 23',
 'UniProt (SwissProt) Alternative ID(s) of Target Chain 23',
 'UniProt (TrEMBL) Submitted Name of Target Chain 23',
 'UniProt (TrEMBL) Entry Name of Target Chain 23',
 'UniProt (TrEMBL) Primary ID of Target Chain 23',
 'UniProt (TrEMBL) Secondary ID(s) of Target Chain 23',
 'UniProt (TrEMBL) Alternative ID(s) of Target Chain 23',
 'BindingDB Target Chain Sequence 24',
 'PDB ID(s) of Target Chain 24',
 'UniProt (SwissProt) Recommended Name of Target Chain 24',
 'UniProt (SwissProt) Entry Name of Target Chain 24',
 'UniProt (SwissProt) Primary ID of Target Chain 24',
 'UniProt (SwissProt) Secondary ID(s) of Target Chain 24',
 'UniProt (SwissProt) Alternative ID(s) of Target Chain 24',
 'UniProt (TrEMBL) Submitted Name of Target Chain 24',
 'UniProt (TrEMBL) Entry Name of Target Chain 24',
 'UniProt (TrEMBL) Primary ID of Target Chain 24',
 'UniProt (TrEMBL) Secondary ID(s) of Target Chain 24',
 'UniProt (TrEMBL) Alternative ID(s) of Target Chain 24',
 'BindingDB Target Chain Sequence 25',
 'PDB ID(s) of Target Chain 25',
 'UniProt (SwissProt) Recommended Name of Target Chain 25',
 'UniProt (SwissProt) Entry Name of Target Chain 25',
 'UniProt (SwissProt) Primary ID of Target Chain 25',
 'UniProt (SwissProt) Secondary ID(s) of Target Chain 25',
 'UniProt (SwissProt) Alternative ID(s) of Target Chain 25',
 'UniProt (TrEMBL) Submitted Name of Target Chain 25',
 'UniProt (TrEMBL) Entry Name of Target Chain 25',
 'UniProt (TrEMBL) Primary ID of Target Chain 25',
 'UniProt (TrEMBL) Secondary ID(s) of Target Chain 25',
 'UniProt (TrEMBL) Alternative ID(s) of Target Chain 25',
 'BindingDB Target Chain Sequence 26',
 'PDB ID(s) of Target Chain 26',
 'UniProt (SwissProt) Recommended Name of Target Chain 26',
 'UniProt (SwissProt) Entry Name of Target Chain 26',
 'UniProt (SwissProt) Primary ID of Target Chain 26',
 'UniProt (SwissProt) Secondary ID(s) of Target Chain 26',
 'UniProt (SwissProt) Alternative ID(s) of Target Chain 26',
 'UniProt (TrEMBL) Submitted Name of Target Chain 26',
 'UniProt (TrEMBL) Entry Name of Target Chain 26',
 'UniProt (TrEMBL) Primary ID of Target Chain 26',
 'UniProt (TrEMBL) Secondary ID(s) of Target Chain 26',
 'UniProt (TrEMBL) Alternative ID(s) of Target Chain 26',
 'BindingDB Target Chain Sequence 27',
 'PDB ID(s) of Target Chain 27',
 'UniProt (SwissProt) Recommended Name of Target Chain 27',
 'UniProt (SwissProt) Entry Name of Target Chain 27',
 'UniProt (SwissProt) Primary ID of Target Chain 27',
 'UniProt (SwissProt) Secondary ID(s) of Target Chain 27',
 'UniProt (SwissProt) Alternative ID(s) of Target Chain 27',
 'UniProt (TrEMBL) Submitted Name of Target Chain 27',
 'UniProt (TrEMBL) Entry Name of Target Chain 27',
 'UniProt (TrEMBL) Primary ID of Target Chain 27',
 'UniProt (TrEMBL) Secondary ID(s) of Target Chain 27',
 'UniProt (TrEMBL) Alternative ID(s) of Target Chain 27',
 'BindingDB Target Chain Sequence 28',
 'PDB ID(s) of Target Chain 28',
 'UniProt (SwissProt) Recommended Name of Target Chain 28',
 'UniProt (SwissProt) Entry Name of Target Chain 28',
 'UniProt (SwissProt) Primary ID of Target Chain 28',
 'UniProt (SwissProt) Secondary ID(s) of Target Chain 28',
 'UniProt (SwissProt) Alternative ID(s) of Target Chain 28',
 'UniProt (TrEMBL) Submitted Name of Target Chain 28',
 'UniProt (TrEMBL) Entry Name of Target Chain 28',
 'UniProt (TrEMBL) Primary ID of Target Chain 28',
 'UniProt (TrEMBL) Secondary ID(s) of Target Chain 28',
 'UniProt (TrEMBL) Alternative ID(s) of Target Chain 28',
 'BindingDB Target Chain Sequence 29',
 'PDB ID(s) of Target Chain 29',
 'UniProt (SwissProt) Recommended Name of Target Chain 29',
 'UniProt (SwissProt) Entry Name of Target Chain 29',
 'UniProt (SwissProt) Primary ID of Target Chain 29',
 'UniProt (SwissProt) Secondary ID(s) of Target Chain 29',
 'UniProt (SwissProt) Alternative ID(s) of Target Chain 29',
 'UniProt (TrEMBL) Submitted Name of Target Chain 29',
 'UniProt (TrEMBL) Entry Name of Target Chain 29',
 'UniProt (TrEMBL) Primary ID of Target Chain 29',
 'UniProt (TrEMBL) Secondary ID(s) of Target Chain 29',
 'UniProt (TrEMBL) Alternative ID(s) of Target Chain 29',
 'BindingDB Target Chain Sequence 30',
 'PDB ID(s) of Target Chain 30',
 'UniProt (SwissProt) Recommended Name of Target Chain 30',
 'UniProt (SwissProt) Entry Name of Target Chain 30',
 'UniProt (SwissProt) Primary ID of Target Chain 30',
 'UniProt (SwissProt) Secondary ID(s) of Target Chain 30',
 'UniProt (SwissProt) Alternative ID(s) of Target Chain 30',
 'UniProt (TrEMBL) Submitted Name of Target Chain 30',
 'UniProt (TrEMBL) Entry Name of Target Chain 30',
 'UniProt (TrEMBL) Primary ID of Target Chain 30',
 'UniProt (TrEMBL) Secondary ID(s) of Target Chain 30',
 'UniProt (TrEMBL) Alternative ID(s) of Target Chain 30',
 'BindingDB Target Chain Sequence 31',
 'PDB ID(s) of Target Chain 31',
 'UniProt (SwissProt) Recommended Name of Target Chain 31',
 'UniProt (SwissProt) Entry Name of Target Chain 31',
 'UniProt (SwissProt) Primary ID of Target Chain 31',

In [81]:
df.head()

,BindingDB Reactant_set_id,Ligand SMILES,Ligand InChI,Ligand InChI Key,BindingDB MonomerID,BindingDB Ligand Name,Target Name,Target Source Organism According to Curator or DataSource,Ki (nM),IC50 (nM),...,UniProt (SwissProt) Recommended Name of Target Chain 50,UniProt (SwissProt) Entry Name of Target Chain 50,UniProt (SwissProt) Primary ID of Target Chain 50,UniProt (SwissProt) Secondary ID(s) of Target Chain 50,UniProt (SwissProt) Alternative ID(s) of Target Chain 50,UniProt (TrEMBL) Submitted Name of Target Chain 50,UniProt (TrEMBL) Entry Name of Target Chain 50,UniProt (TrEMBL) Primary ID of Target Chain 50,UniProt (TrEMBL) Secondary ID(s) of Target Chain 50,UniProt (TrEMBL) Alternative ID(s) of Target Chain 50
0,9825,COc1cc2c(Nc3ccc(Cl)cc3Cl)c(cnc2cc1OCCCN1CCN(C)...,InChI=1S/C25H27Cl2N5O2/c1-31-7-9-32(10-8-31)6-...,MVQUQGLRQPMJPU-UHFFFAOYSA-N,4521,"4-[(2,4-dichlorophenyl)amino]-6-methoxy-7-[3-(...",Proto-oncogene tyrosine-protein kinase Src,Homo sapiens,NaN,8.7,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,9826,COc1cc2c(Nc3cc(OC)c(OC)c(OC)c3)c(cnc2cc1OCCCN1...,InChI=1S/C28H35N5O5/c1-32-8-10-33(11-9-32)7-6-...,VOUVVBUKNLBXGS-UHFFFAOYSA-N,6121,6-methoxy-7-[3-(4-methylpiperazin-1-yl)propoxy...,Proto-oncogene tyrosine-protein kinase Src,Homo sapiens,NaN,5.1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,9827,COCCOc1cc2ncc(C#N)c(Nc3cc(OC)c(Cl)cc3Cl)c2cc1O...,InChI=1S/C23H23Cl2N3O5/c1-29-4-6-32-21-8-15-18...,VXEOIAFZWQMOEP-UHFFFAOYSA-N,6122,"4-[(2,4-dichloro-5-methoxyphenyl)amino]-6,7-bi...",Proto-oncogene tyrosine-protein kinase Src,Homo sapiens,NaN,2.8,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,9828,COCCOc1cc2ncc(C#N)c(Nc3ccc(Cl)cc3Cl)c2cc1OCCOC,InChI=1S/C22H21Cl2N3O4/c1-28-5-7-30-20-10-16-1...,DTLASHUZTAPRBX-UHFFFAOYSA-N,6123,"4-[(2,4-dichlorophenyl)amino]-6,7-bis(2-methox...",Proto-oncogene tyrosine-protein kinase Src,Homo sapiens,NaN,12,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,9829,COCCOc1cc2ncc(C#N)c(Nc3cc(OC)c(OC)c(OC)c3)c2cc...,InChI=1S/C25H29N3O7/c1-29-6-8-34-20-12-18-19(1...,BTBPPLGKNLXRGR-UHFFFAOYSA-N,6124,"6,7-bis(2-methoxyethoxy)-4-[(3,4,5-trimethoxyp...",Proto-oncogene tyrosine-protein kinase Src,Homo sapiens,NaN,25,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [82]:
df=df[['Ligand SMILES', 'BindingDB Target Chain Sequence 1', 'IC50 (nM)']]

In [83]:
df.shape

(54968, 3)

In [84]:
from rdkit import Chem
from rdkit.Chem import AllChem

In [85]:
df = df[df["Ligand SMILES"].notna()].copy()

def smiles_to_fp(smiles):
    mol = Chem.MolFromSmiles(smiles)
    if mol is None:
        return None
    return list(AllChem.GetMorganFingerprintAsBitVect(mol, 2, 2048))

df["fingerprint"] = df["Ligand SMILES"].apply(smiles_to_fp)
df = df[df["fingerprint"].notna()].copy()

In [86]:
df

,Ligand SMILES,BindingDB Target Chain Sequence 1,IC50 (nM),fingerprint
0,COc1cc2c(Nc3ccc(Cl)cc3Cl)c(cnc2cc1OCCCN1CCN(C)...,MGSNKSKPKDASQRRRSLEPAENVHGAGGGAFPASQTPSKPASADG...,8.7,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, ..."
1,COc1cc2c(Nc3cc(OC)c(OC)c(OC)c3)c(cnc2cc1OCCCN1...,MGSNKSKPKDASQRRRSLEPAENVHGAGGGAFPASQTPSKPASADG...,5.1,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, ..."
2,COCCOc1cc2ncc(C#N)c(Nc3cc(OC)c(Cl)cc3Cl)c2cc1O...,MGSNKSKPKDASQRRRSLEPAENVHGAGGGAFPASQTPSKPASADG...,2.8,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, ..."
3,COCCOc1cc2ncc(C#N)c(Nc3ccc(Cl)cc3Cl)c2cc1OCCOC,MGSNKSKPKDASQRRRSLEPAENVHGAGGGAFPASQTPSKPASADG...,12,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, ..."
4,COCCOc1cc2ncc(C#N)c(Nc3cc(OC)c(OC)c(OC)c3)c2cc...,MGSNKSKPKDASQRRRSLEPAENVHGAGGGAFPASQTPSKPASADG...,25,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, ..."
...,...,...,...,...
92691,CC[C@H]1C[C@@H]2C[C@@H]3[C@H]1N(C2)CCc1c3[nH]c...,MGRRRQGPAQPASELPARNACLLPNGSAWLPGWAEPDGNGSAGPQD...,21000,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..."
92695,CC[C@H]1C[C@@H]2C[C@@H]3[C@H]1N(C2)CCc1c3[nH]c...,MDSSTGPGNTSDCSDPLAQASCSPAPGSWLNLSHVDGNQSDPCGLN...,26000,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..."
92710,CC[C@H]1C[C@@H]2C[C@@H]3[C@H]1N(C2)CCc1c3[nH]c...,MRGAGGPRGPRGPAKMLLLLALACASPFPEEVPGPGAVGGGTGGAR...,3200,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..."
92711,CC[C@H]1C[C@@H]2C[C@@H]3[C@H]1N(C2)CCc1c3[nH]c...,MRGAGGPRGPRGPAKMLLLLALACASPFPEEVPGPGAVGGGTGGAR...,5200,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..."
92715,CC[C@H]1C[C@@H]2C[C@@H]3[C@H]1N(C2)CCc1c3[nH]c...,MRIICRQIVLLFSGFWGLAMGAFPSSVQIGGLFIRNTDQEYTAFRL...,50500,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..."

In [87]:
from collections import Counter
import pandas as pd

aa_list = list("ACDEFGHIKLMNPQRSTVWY")

def aac(seq):
    seq = seq.upper()
    counts = Counter(seq)
    length = len(seq)
    return [counts[aa] / length for aa in aa_list]

df["AAC"] = df["BindingDB Target Chain Sequence 1"].apply(aac)

In [88]:
df = df[['fingerprint', 'AAC', 'IC50 (nM)']]

In [89]:
df.head()

,fingerprint,AAC,IC50 (nM)
0,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, ...","[0.08208955223880597, 0.016791044776119403, 0....",8.7
1,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, ...","[0.08208955223880597, 0.016791044776119403, 0....",5.1
2,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, ...","[0.08208955223880597, 0.016791044776119403, 0....",2.8
3,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, ...","[0.08208955223880597, 0.016791044776119403, 0....",12
4,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, ...","[0.08208955223880597, 0.016791044776119403, 0....",25

In [90]:
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error, r2_score

In [91]:
X = df.apply(
    lambda row: row["fingerprint"] + row["AAC"],
    axis=1
)

X = pd.DataFrame(X.tolist())

y = df["IC50 (nM)"]

In [92]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    random_state=42
)

In [93]:
model = RandomForestRegressor(
    n_estimators=200,
    random_state=42,
    n_jobs=-1
)

model.fit(X_train, y_train)

RandomForestRegressor(n_estimators=200, n_jobs=-1, random_state=42)

In [96]:
pred = model.predict(X_test)

In [97]:
rmse = np.sqrt(mean_squared_error(y_test, pred))
r2 = r2_score(y_test, pred)

print("RMSE:", rmse)
print("R²:", r2)

RMSE: 3105310.7011856646
R²: 0.7036082314734189

In [99]:
import numpy as np

from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import cross_validate

In [100]:
scores = cross_validate(
    model,
    X,
    y,
    cv=5,
    scoring=("r2", "neg_root_mean_squared_error"),
    return_train_score=False
)

In [101]:
rmse = -scores["test_neg_root_mean_squared_error"]
r2 = scores["test_r2"]

print("RMSE folds:", rmse)
print("Mean RMSE:", rmse.mean())

print("R² folds:", r2)
print("Mean R²:", r2.mean())

RMSE folds: [1532933.20975589 1132175.31677355 1852023.20818483 8057504.8330293
 2914290.68718377]
Mean RMSE: 3097785.4509854675
R² folds: [-8.51770908e+01 -1.12174636e+02 -7.28810837e-01 -4.04252891e-03
 -4.70609099e-02]
Mean R²: -39.62632814842