In [32]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
import os

os.chdir(r"C:\Users\hempe\Studium\Masterthesis\Repository\Masterthesis")

In [33]:
# Datensatz aus BindingDB_BindingDB_Articles.tsv mit UTF-8-Encoding laden
df = pd.read_csv('data/raw/BindingDB_BindingDB_Articles.tsv', sep='\t', encoding='utf-8', usecols=['Ligand SMILES', 'BindingDB Target Chain Sequence 1', 'IC50 (nM)'])

C:\Users\hempe\AppData\Local\Temp\ipykernel_41448\2458185884.py:2: DtypeWarning: Columns (9) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('data/raw/BindingDB_BindingDB_Articles.tsv', sep='\t', encoding='utf-8', usecols=['Ligand SMILES', 'BindingDB Target Chain Sequence 1', 'IC50 (nM)'])

In [34]:
#Select relevant feaures
df.head()

,Ligand SMILES,IC50 (nM),BindingDB Target Chain Sequence 1
0,COc1cc2c(Nc3ccc(Cl)cc3Cl)c(cnc2cc1OCCCN1CCN(C)...,8.7,MGSNKSKPKDASQRRRSLEPAENVHGAGGGAFPASQTPSKPASADG...
1,COc1cc2c(Nc3cc(OC)c(OC)c(OC)c3)c(cnc2cc1OCCCN1...,5.1,MGSNKSKPKDASQRRRSLEPAENVHGAGGGAFPASQTPSKPASADG...
2,COCCOc1cc2ncc(C#N)c(Nc3cc(OC)c(Cl)cc3Cl)c2cc1O...,2.8,MGSNKSKPKDASQRRRSLEPAENVHGAGGGAFPASQTPSKPASADG...
3,COCCOc1cc2ncc(C#N)c(Nc3ccc(Cl)cc3Cl)c2cc1OCCOC,12,MGSNKSKPKDASQRRRSLEPAENVHGAGGGAFPASQTPSKPASADG...
4,COCCOc1cc2ncc(C#N)c(Nc3cc(OC)c(OC)c(OC)c3)c2cc...,25,MGSNKSKPKDASQRRRSLEPAENVHGAGGGAFPASQTPSKPASADG...

In [35]:
#show me number of rows and columns
df.shape

(94219, 3)

In [36]:
# Alle Datensätze mit fehlenden Werten in den Spalten
# IC50 (nM), BindingDB Target Chain Sequence 1 und Ligand SMILES entfernen
df = df[['Ligand SMILES', 'BindingDB Target Chain Sequence 1', 'IC50 (nM)']].dropna()

In [37]:
#show me number of rows and columns
df.shape

(63634, 3)

In [39]:
# Spalte IC50 (nM) in numerische Werte umwandeln
# Nicht-numerische Werte werden zu NaN und anschließend entfernt
df['IC50 (nM)'] = pd.to_numeric(df['IC50 (nM)'], errors='coerce')
df = df.dropna(subset=['IC50 (nM)'])

In [24]:
#show me number of rows and columns
df.shape

(54968, 3)

In [25]:
# Alle Datensätze entfernen, bei denen IC50 <= 0 oder IC50 > 10.000.000 nM ist
df = df[(df['IC50 (nM)'] > 0) & (df['IC50 (nM)'] <= 10000000)]

In [26]:
#show me number of rows and columns
df.shape

(54924, 3)

In [27]:
# IC50-Werte von nM in Molar (M) umrechnen
df["IC50 (nM)"] = df["IC50 (nM)"] * 1e-9

# IC50-Werte durch negative dekadische Logarithmierung in pIC50 transformieren
df["IC50 (nM)"] = -np.log10(df["IC50 (nM)"])

# Rename the column "IC50 (nM)" to "pIC50"
df = df.rename(columns={"IC50 (nM)": "pIC50"})

In [28]:
df.head()

,Ligand SMILES,BindingDB Target Chain Sequence 1,pIC50
0,COc1cc2c(Nc3ccc(Cl)cc3Cl)c(cnc2cc1OCCCN1CCN(C)...,MGSNKSKPKDASQRRRSLEPAENVHGAGGGAFPASQTPSKPASADG...,8.060481
1,COc1cc2c(Nc3cc(OC)c(OC)c(OC)c3)c(cnc2cc1OCCCN1...,MGSNKSKPKDASQRRRSLEPAENVHGAGGGAFPASQTPSKPASADG...,8.292430
2,COCCOc1cc2ncc(C#N)c(Nc3cc(OC)c(Cl)cc3Cl)c2cc1O...,MGSNKSKPKDASQRRRSLEPAENVHGAGGGAFPASQTPSKPASADG...,8.552842
3,COCCOc1cc2ncc(C#N)c(Nc3ccc(Cl)cc3Cl)c2cc1OCCOC,MGSNKSKPKDASQRRRSLEPAENVHGAGGGAFPASQTPSKPASADG...,7.920819
4,COCCOc1cc2ncc(C#N)c(Nc3cc(OC)c(OC)c(OC)c3)c2cc...,MGSNKSKPKDASQRRRSLEPAENVHGAGGGAFPASQTPSKPASADG...,7.602060

In [29]:

# Alle Datensätze mit fehlenden Werten in den Spalten
# IC50 (nM), BindingDB Target Chain Sequence 1 und Ligand SMILES entfernen
df = df[['Ligand SMILES', 'BindingDB Target Chain Sequence 1', 'IC50 (nM)']].dropna()

# Spalte IC50 (nM) in numerische Werte umwandeln
# Nicht-numerische Werte werden zu NaN und anschließend entfernt
df['IC50 (nM)'] = pd.to_numeric(df['IC50 (nM)'], errors='coerce')
df = df.dropna(subset=['IC50 (nM)'])

# Alle Datensätze entfernen, bei denen IC50 <= 0 oder IC50 > 10.000.000 nM ist
df = df[(df['IC50 (nM)'] > 0) & (df['IC50 (nM)'] <= 10000000)]

# IC50-Werte von nM in Molar (M) umrechnen
IC50_M = df["IC50 (nM)"] * 1e-9

# IC50-Werte durch negative dekadische Logarithmierung in pIC50 transformieren
df["pIC50"] = -np.log10(IC50_M)

# Datensatz in Trainings- und Testdaten aufteilen
train_df, test_df = train_test_split(df, test_size=0.2, random_state=42)

KeyError: "['IC50 (nM)'] not in index"

In [ ]:
# Trainings- und Testdaten als separate CSV-Dateien speichern
train_df.to_csv('data/processed/train_data.csv', index=False)
test_df.to_csv('data/processed/test_data.csv', index=False)

# Erfolgsmeldung mit Größe der Trainings- und Testdaten ausgeben
print(f'✅ Data set was splitted. Train data size: {train_df.shape}, Test data size: {test_df.shape}')

✅ Data set was splitted. Train data size: (43939, 4), Test data size: (10985, 4)